### ISSUE TITLE
How can i save fields from M:N relation? 

### ISSUE THREAD

**Issue by hermesalvesbr** [rezo-labs/directus-extension-computed-interface#1]
Hi there,

Thanks for your extension! I'm trying to make a shopping cart inside directus:

![image](https://user-images.githubusercontent.com/379850/194910063-7d287160-f53a-4304-90b5-667a0849c5ae.png)

How can i capture the selected values from a table relationship? Do you have another idea to do a shopping cart inside directus app?

**Comment by Guiqft** [comment]
Hi! I have the same use case and created a PR to allow it. 
Hope this helps 

open to review and suggestions 🚀

**Comment by hermesalvesbr** [comment]
Thanks @Guiqft  for this partnership! Maybe i found a bug, when use with readonly input fields.
