### ISSUE TITLE
Usage : In display conditionnal

### ISSUE THREAD

**Issue by nervusdm** [rezo-labs/directus-extension-computed-interface#16]
Thanks for this really good Module.
Can we use it for display conditionnal, one way or another ?

I would like to use GT(A,B) and if true, show it in red color for example.

**Comment by duydvu** [comment]
Hi @nervusdm 

Have you tried the Boolean display? 
<img width="850" alt="Screen Shot 2022-11-22 at 08 45 24" src="https://user-images.githubusercontent.com/23261928/203196641-cce6177c-1bf1-4c32-a624-7ba41d6fead8.png">
