### ISSUE TITLE
Input 'field' attribute is missing

### ISSUE THREAD

**Issue by mutil** [rezo-labs/directus-extension-computed-interface#22]
All other directus input fields have a `field` attribute. Can you please add it for consistency? 
For my use case, this is needed for selecting the input and doing further manipulations in another interface.

**Comment by duydvu** [comment]
Hi @mutil , I do not quite understand your problem. Could you make it clear?

**Comment by mutil** [comment]
Hi @duydvu,

In my custom slug extension I have this code:  `document.querySelector("input[field=name]")`.
This works with the default input interface but not with the computed one, because it’s missing `field` on the input element.

Generated html of default input:
`<input loading="false" width="0" collection="artists" field="name" field-data="[object Object]" primary-key="10" autocomplete="off" type="text" step="1" data-v-54898a1e="">`

Generated html of computed input:
`<input loading="false" width="0" field-data="[object Object]" length="255" autocomplete="off" type="string" step="1" data-v-54898a1e="">`

As a side note, I believe `type="string"` is not valid value for the `type` attribute and maybe `collection` and `primary-key` could be added also.

**Comment by duydvu** [comment]
OK I understand. I will add it to the next version.
