### ISSUE TITLE
Is it still a it works?

### ISSUE THREAD

**Issue by pixelkoduje** [rezo-labs/directus-extension-computed-interface#23]
I have a field o2m, I write in a calculated field ASUM(feedback, rating)
I'm getting 0 all the time. The add-on is no longer being developed, right? And in directus 9 it doesn't work?

**Comment by duydvu** [comment]
We are still working on it. But we have a lot of other jobs to prioritize so updates may not come frequently.

If you encounter bugs, please show us your environment & steps to reproduce them so we can identify the root cause.
