### ISSUE TITLE
Lateral String

### ISSUE THREAD

**Issue by in2uitions** [rezo-labs/directus-extension-computed-interface#31]
Hello,

I know you have stated that lateral string does not work, but is there any turnaround for it?
I have created the below computed value and i need it to run when discount_type is "value", how can i reach this?

{{IF(EQUAL(discount_type, "value"), SUM(subtotal, discount_value), subtotal)}}

Thanks

**Comment by duydvu** [comment]
One workaround that I can find is to encode the discount_type to integer values. For example, 0 for "value" and 1 for others.

To actually use literal strings, I think I have an idea but need some time to test it
