### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by mtgomes** [rezo-labs/directus-extension-computed-interface#32]
Hi,
I'm hosting directus using coolify. Unfortunately, when I install the package and restart, coolify pulls a new image, so the packages are gone.
Would it be possible to provide the index.js files that I can put in the folders? 
Some extensions provide it and I've installed them successfully by putting the files in the folders. I don't know how to generate them myself, so if you could provide them it would be great. 
Thanks a lot!
Manuel

**Comment by duydvu** [comment]
You can use this command to download the package with the latest version:
```
wget $(npm view directus-extension-computed-interface dist.tarball)
```
Or if you want to download a specific version, download this link
```
https://registry.npmjs.org/directus-extension-computed-interface/-/directus-extension-computed-interface-1.4.1.tgz
```
Then extract the package and the `index.js` file should be in the `package/dist` folder.

**Comment by mtgomes** [comment]
Thanks. Will give it a shot!
