### ISSUE TITLE
Not support multiple computed interface in one item

### ISSUE THREAD

**Issue by huhongbo** [rezo-labs/directus-extension-computed-interface#36]
directus version:
9.23.4
how to reproduce the problem:
create a new table test
add one input field named "h" ,type int
create  three computed fields:
a 
{{ MULTIPLY(3,h) }}
b
{{ MULTIPLY(4,h) }}
c
{{ MULTIPLY(5,h) }}
when submitted, only c's value will be submitted, a and b will be empty

**Comment by duydvu** [comment]
Hi @huhongbo, thank you for reporting.

Luckily, this issue was fixed in the latest version (1.5.0) via #34. You can try upgrading the extension and test again.
If the issue still persists, let me know.
