### ISSUE TITLE
Possible new Relational Operators

### ISSUE THREAD

**Issue by LevelUpGit** [rezo-labs/directus-extension-computed-interface#45]
We have a case when we need to display MAX and MIN for related table, currently I don't see a way to get it. Possible solution would work same a ASUM, just with MAX and MIN, AMAX and AMIN, and possibly other operators.

**Comment by duydvu** [comment]
This will be the list of relational operators that I come up with, feel free to add more:
- AMIN: min
- AMAX: max
- AAVG: average
- AMUL: multiply
- AAND: and
- AOR: or

**Comment by LevelUpGit** [comment]
I can't think of any, thank you :)
