### ISSUE TITLE
ASUM and ARRAY_LEN doesn't work if there are more than 22 items

### ISSUE THREAD

**Issue by LevelUpGit** [rezo-labs/directus-extension-computed-interface#46]
We are getting 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE'" when there are more than 22 items for calculation using operators ASUM and ARRAY_LEN.

Possible issues:
https://github.com/directus/directus/discussions/16659
https://github.com/directus/directus/issues/16745

**Comment by duydvu** [comment]
Yeah, `_in` is used to filter ids of O2M items.

It seems that the issue will be solved in the near future. But to support older versions, it needs a workaround.
https://github.com/directus/directus/issues/16745#issuecomment-1377828578 sound good to me.
