### ISSUE TITLE
Feature request/check

### ISSUE THREAD

**Issue by nalognl** [rezo-labs/directus-extension-computed-interface#48]
Should computes field be calculated on entry open event ? It will be useful because now it calculate only if something changes. 

Also it only calculate result and input to field but after entry save the value not saved to db. Is it expected result ? The value saved only in case field mode not set to Read Only or Display Only

**Comment by duydvu** [comment]
> Should computes field be calculated on entry open event ? It will be useful because now it calculate only if something changes.

Yes, using the computed field without other fields is currently impossible. The good news is that this may be changed in the future as in my reply in #43 .



> Also it only calculate result and input to field but after entry save the value not saved to db. Is it expected result ? The value saved only in case field mode not set to Read Only or Display Only

If you want to save the value to db, you should set Field Mode to null or "Read Only". "Display Only" only calculates a representation value to display in the UI.
