### ISSUE TITLE
Sum more than two fields

### ISSUE THREAD

**Issue by antikkorps** [rezo-labs/directus-extension-computed-interface#5]
Hi!

First thanks for the plugin which is something I was searching for.
I am facing an issue if I want to add more than two fields. 
In my case I have 6 fields to add. I tried several combination but dit not manage to make it work.

Again thank you that is a very useful extension.

**Comment by duydvu** [comment]
Have you tried this:
```
{{ SUM(field1, SUM(field2, SUM(field3, SUM(field4, SUM(field5, field6))))) }}
```
I know it looks bad but it does the job :D

**Comment by antikkorps** [comment]
Yes I tried but I had results like 00.1.230...
So I double checked with your response and saw I had one closing bracket on one field that was in the middle of all the brackets... So sorry about opening an issue on that...
By the way, one improvement which would be nice is to be able to choose directly the label instead of typing it manually.

Thank you very much for your prompt help on it!
