### ISSUE TITLE
Sum Values is not working

### ISSUE THREAD

**Issue by zozito** [rezo-labs/directus-extension-computed-interface#50]
Hi team,

I'm using Directus v10.4.2 with the version extension 1.8.0

I don't know if I'm doing something wrong, but I can't do SUM

This is the template I'm doing {{ SUM(alimentacao, outro) }}

When I enter the values, the computed field concat the numbers instead sum.

![image](https://github.com/rezo-labs/directus-extension-computed-interface/assets/4005288/595c0ded-a79e-4834-9897-1de5e0d00348)

I'm doing something wrong?

Thank you

**Comment by duydvu** [comment]
Hi @zozito , it seems that the 2 fields you are using are strings, so it will concat when using SUM.

In this case, you should convert the fields to float or integer before summing.

The template should be `{{ SUM(INT(alimentacao), INT(outro)) }}`.

**Comment by zozito** [comment]
Hi thank you,

I all the fields and created again as Integer, and it's working :)

Now I want to add another field is a computed result, but it seems I got an error

the field is "custoviagem"

{{ SUM(custoviagem, alimentacao, outro) }} 

custoviagem field have this template:

{{ MULTIPLY(KMs,0.20) }} 

Everytime I put the value on field "alimentacao" I got this error

![image](https://github.com/rezo-labs/directus-extension-computed-interface/assets/4005288/ebf493ee-7d3c-4cc2-812d-209ec0ee3e51)

I'm sorry about my questions I'm new here...

Big hug!

**Comment by zozito** [comment]
I found a way to SUM all the fields with formula

`{{ SUM(SUM(MULTIPLY(KMs,0.20),alimentacao),outro) }} `

![image](https://github.com/rezo-labs/directus-extension-computed-interface/assets/4005288/22e13089-51cf-486f-b456-b1c4e8b9627c)


this is the correct way to do it?

**Comment by duydvu** [comment]
Yes, it is correct. `SUM` only accept 2 arguments so if you want to sum more than 2 fields, you need to use multiple `SUM`.

**Comment by zozito** [comment]
Great :D I'm happy with it.

Let me do another question with compute fields it's possible to calculate de days between dates?

I tried some combinations but I didn't find any solution. :(

Thank you

**Comment by duydvu** [comment]
You just have to convert and subtract 2 dates and divide by the number of milliseconds in a day (86400000).
`{{ DIVIDE(SUBTRACT(DATE(a), DATE(b)), 86400000) }}`

**Comment by zozito** [comment]
Worked, Thank you for your help
