### ISSUE TITLE
Computed Field are not getting date from DateTime Field

### ISSUE THREAD

**Issue by zozito** [rezo-labs/directus-extension-computed-interface#51]
Hi,

I'm using Directus 10.5.2 and now the computed fields are not getting dates

Reproduce:
Create DateTime Field with name date
Create Computed Field

use the formula {{ YEAR(date) }}

When you set a date, the computed field should show the year of the selected date, but doesn't return anything.

I saw in the browser console this beaver 

![image](https://github.com/rezo-labs/directus-extension-computed-interface/assets/4005288/602a8dbb-49ee-443c-9d38-7d5f7e795a6e)

If you use the formula {{ YEAR($NOW)}} the field returns the correct year 2023

![image](https://github.com/rezo-labs/directus-extension-computed-interface/assets/4005288/5eeb0cc4-120d-41fe-b5e2-997ef55159d3)

Can you help me understand if I do something wrong?

Thank you

**Comment by duydvu** [comment]
Hi @zozito , sorry for the late reply.

I confirmed that the issue was caused by upgrading to Directus v10.5.2, reverting back to v10.4.3 fixes the issue.

I'm investigating the problem. When the fix is available, you can return to v10.5.2.

Thanks
