### ISSUE TITLE
Documentation on field names

### ISSUE THREAD

**Issue by finn-e** [rezo-labs/directus-extension-computed-interface#52]
The documentation could use more examples and get started & syntax sections. In particular, it would be nice if there was information about how to format field names in the syntax section. It seems that you can look for related fields. but the syntax for nested relations escapes me. I looked at the code and it looks like we're getting the relationship functions from Directus. Do they have any documentation on this we could link out to?

**Comment by duydvu** [comment]
Hi @finn-e ,

Currently, you can only have access to the first level of relation fields (e.g. `products.items`) so only O2M and M2O are usable as M2M needs level 2.

If you are having trouble debugging your template, you could try enabling the "Debug Mode" option to observe the value of each component in the template.

As for the documentation, I will update it later.
