### ISSUE TITLE
O2M relation operations failing

### ISSUE THREAD

**Issue by falmanna** [rezo-labs/directus-extension-computed-interface#56]
Hey, 

I am having a problem configuring a M2O computed field. The logs are showing the following error:
http://localhost:8055/items/[object%20Object]/2?fields[]=child (403 Forbidden)

Here are my test collections

parent:
<img width="652" alt="Screenshot 2023-08-19 124245" src="https://github.com/rezo-labs/directus-extension-computed-interface/assets/3227740/f7edcae4-1aba-48c6-9296-ba4ceaf5d80d">

child:
<img width="640" alt="Screenshot 2023-08-19 124332" src="https://github.com/rezo-labs/directus-extension-computed-interface/assets/3227740/2ebe5d4b-5e52-4b68-a943-cd45874507f2">

computed field:
<img width="1146" alt="Screenshot 2023-08-19 124313" src="https://github.com/rezo-labs/directus-extension-computed-interface/assets/3227740/17c70a56-e629-475b-bc4e-9aa6d6b0a4ab">

error:
<img width="1684" alt="Screenshot 2023-08-19 124412" src="https://github.com/rezo-labs/directus-extension-computed-interface/assets/3227740/7f4e40ad-4ca0-4515-b8da-4f1b813cad44">

Directus version 10.5.3

**Comment by duydvu** [comment]
Found the bug. Thanks for reporting!
