### ISSUE TITLE
Calculations not work for decimal data type

### ISSUE THREAD

**Issue by pdesuze** [rezo-labs/directus-extension-computed-interface#59]
Using directus 10.5.3 Need accurate calculations when using sum on decimal data type field getting weird concatenation when displaying as a string in the computational field or no calculations at all. 

Please help.

Phil.

**Comment by duydvu** [comment]
Hi @pdesuze ,

Without the information about your template and other field's data types, I can't figure out what the root cause is.

But if I have to guess, it's possible that your SUM contains at least a string, so it will concatenate. You can try wrapping the fields inside `FLOAT()` to make sure that they are converted to float before summing.

**Comment by pdesuze** [comment]
One field that is FLOAT() with a precision of 24 and the other field of type decimal, however the actual Compute Field is of the type string with the following template {{ CURRENCY(SUM(IPC_Amt, Interest)) }}

**Comment by duydvu** [comment]
Well, your setup is valid. If summing causes the 2 numbers to be concatenated, it must be that one of them is a string.

To debug this, you need to enable the **Debug Mode** option in the interface setting.
After enabling it, open the Developer Tool console and make changes to the fields. Observe the step-by-step calculation.

It will be more helpful if you can provide some examples or a step-by-step reproduce

**Comment by pdesuze** [comment]
Was able to solve by actually making one field a string because float was rounding up. When decimals type are use there is concatenation so something to look into. But I was able to use this template to get it to work: 

{{ CURRENCY(SUM(FLOAT(IPC_Amt), Interest)) }}
