### ISSUE TITLE
displayOnly prevents computed value to be updated

### ISSUE THREAD

**Issue by Guiqft** [rezo-labs/directus-extension-computed-interface#6]
Checking the code, when `props.displayOnly` is true, we dont emit our new computed values, just show on the screen. 
I think that's not the expected behavior, `displayOnly` should means that you can't directly edit the field, but you still wish that the value will be saved on database.

**Comment by duydvu** [comment]
Actually, my intention for `displayOnly` is to serve as an alias field as written in README. Your suggestion is more like `readOnly`, you can create a new option to serve that purpose.

**Comment by Guiqft** [comment]
Sure @duydvu. Thanks for the answer.
